name: CD to Kubernetes Cluster

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-k8s:
    runs-on: ubuntu-latest
    needs: build-and-push
    environment: K8S-SECRETS
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      - name: Deploy to remote server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            chmod +x ./deploy_k8s.sh
            ./deploy_k8s.sh